parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''
  toolchain: 'stable'

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      tc: ${{ parameters.toolchain }}
    steps:
      - powershell: |
          echo "2: $env:TC"
          echo "4: $(tc)"
          Invoke-WebRequest -Uri "https://win.rustup.rs" -OutFile "rustup-init.exe"
          &".\rustup-init.exe" --default-toolchain $(tc) -y
        displayName: 'Install Rust'
      - powershell: |
          &"$env:USERPROFILE\.cargo\bin\cargo" build -p spectacles --release
        displayName: 'Build Spectacles'
      - task: GithubRelease@0
      - displayName: 'Package GitHub release'
        inputs:
          githubConnection: spec-tacles
          repositoryName: spec-tacles-spectacles-rs
          assets: $(Build.ArtifactStagingDirectory)/*.exe