parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''
  toolchain: 'stable'

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      tc: ${{ parameters.toolchain }}
    steps:
      - bash: |
          curl -o rustup-init.sh https://sh.rustup.rs -sSf
          sh rustup-init.sh --default-toolchain $(tc) -y
        displayName: 'Install Rust'
      - bash: |
          source $HOME/.cargo/env
          cargo build -p spectacles --release
          zip spectacles.zip target/release/spectacles
        displayName: 'Build Spectacles'
      - task: GithubRelease@0
          inputs:
            githubConnection: spec-tacles
            repositoryName: spec-tacles-spectacles-rs
            assets: $(Build.ArtifactStagingDirectory)/*.zip